const BASE=import.meta.env.VITE_API_BASE_URL||'/api/v1'
let token=localStorage.getItem('customer_token')||''
let companyToken=localStorage.getItem('booking_company_token')||''
async function request<T>(path:string,options:RequestInit={}){const response=await fetch(`${BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...options.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail||'Unable to complete your request');return body as T}
export const auth={set:(value:string)=>{token=value;localStorage.setItem('customer_token',value)},clear:()=>{token='';localStorage.removeItem('customer_token')},has:()=>!!token}
async function companyRequest<T>(path:string,options:RequestInit={}){const response=await fetch(`${BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(companyToken?{Authorization:`Bearer ${companyToken}`}:{ }),...options.headers}});const body=response.status===204?{}:await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail||'Unable to complete your request');return body as T}
export const companyAuth={set:(value:string)=>{companyToken=value;localStorage.setItem('booking_company_token',value)},clear:()=>{companyToken='';localStorage.removeItem('booking_company_token')},has:()=>!!companyToken}
export const companyApi={login:(body:object)=>companyRequest<CompanyAuthResponse>('/company-auth/login',{method:'POST',body:JSON.stringify(body)}),register:(body:object)=>companyRequest<CompanyAuthResponse>('/company-auth/register',{method:'POST',body:JSON.stringify(body)}),profile:()=>companyRequest<CompanyProfile>('/company/profile'),saveProfile:(body:object)=>companyRequest<CompanyProfile>('/company/profile',{method:'PUT',body:JSON.stringify(body)}),logo:async()=>{const response=await fetch(`${BASE}/company/profile/logo`,{headers:{Authorization:`Bearer ${companyToken}`}});if(!response.ok)throw new Error('Unable to load company logo');return response.blob()},uploadLogo:(file:File)=>companyRequest<CompanyProfile>('/company/profile/logo',{method:'PUT',headers:{'Content-Type':file.type},body:file}),references:()=>companyRequest<{vehicle_classes:Array<{id:string;code:string;name:string}>}>('/company/reference-data'),catalog:(kind:string)=>companyRequest<{items:CatalogItem[]}>(`/company/catalog/${kind}`),create:(kind:string,body:object)=>companyRequest(`/company/catalog/${kind}`,{method:'POST',body:JSON.stringify(body)}),update:(kind:string,id:string,body:object)=>companyRequest(`/company/catalog/${kind}/${id}`,{method:'PATCH',body:JSON.stringify(body)}),remove:(kind:string,id:string)=>companyRequest(`/company/catalog/${kind}/${id}`,{method:'DELETE'})}
export const api={brand:()=>request<{name:string;currency:string;usd_to_dop:string}>('/brand'),locations:()=>request<Location[]>('/locations'),catalogVersion:()=>request<{version:string}>(`/catalog-version?t=${Date.now()}`),search:(query:URLSearchParams)=>request<SearchResponse>(`/availability?${query}`),addOns:(supplierId:string)=>request<{supplier_name:string;items:AddOn[]}>(`/suppliers/${supplierId}/add-ons`),login:(body:object)=>request<AuthResponse>('/auth/login',{method:'POST',body:JSON.stringify(body)}),register:(body:object)=>request<AuthResponse>('/auth/register',{method:'POST',body:JSON.stringify(body)}),logout:()=>request<void>('/auth/logout',{method:'POST'}),profile:()=>request<CustomerProfile>('/me/profile'),updateProfile:(body:CustomerProfile)=>request<CustomerProfile>('/me/profile',{method:'PUT',body:JSON.stringify(body)}),book:(body:object)=>request<BookingResult>('/reservations',{method:'POST',body:JSON.stringify(body)}),trips:()=>request<Trip[]>('/me/reservations')}
export type Location={id:string;code:string;name:string;city:string;country_code:string;location_type:string}
export type Car={supplier_company_id:string;supplier_name:string;pickup_location_id:string;return_location_id:string;vehicle_class_id:string;class_code:string;name:string;description?:string;passenger_capacity:number;luggage_capacity:number;door_count:number;transmission:string;fuel_type:string;make?:string;model?:string;model_year?:number;rate_plan_price_id:string;rate_plan_id:string;rate_plan_name:string;currency_code:string;rate_amount:string;rental_days:number;total:string;usd_to_dop:string;tax_rates:Array<{tax_code:string;name:string;rate_percent:string}>}
export type SearchResponse={pickup_at:string;return_at:string;driver_age:number;items:Car[]}
export type AddOn={id:string;extra_code:string;name:string;description?:string;billing_basis:'PER_DAY'|'PER_RENTAL'|'ONE_TIME';default_unit_price:string;currency_code:string;taxable:boolean}
export type CustomerProfile={first_name:string;last_name:string;email:string;phone_number?:string;address_line_1?:string;address_line_2?:string;city?:string;state_region?:string;postal_code?:string;country_code?:string}
export type AuthResponse={access_token:string;customer:CustomerProfile}
export type BookingResult={id:string;reservation_number:string;status:string;currency_code:string;quoted_total:string}
export type CompanyAuthResponse={access_token:string;company:{id:string;company_code:string;display_name:string};user:{display_name:string}}
export type CompanyProfile={id:string;company_code:string;display_name:string;legal_name:string;address_line_1?:string;address_line_2?:string;city?:string;state_region?:string;postal_code?:string;country_code:string;phone_number?:string;email?:string;default_currency_code:string;has_logo:boolean}
export type CatalogItem={id:string;vehicle_class_id?:string;class_code?:string;vehicle_class_name?:string;billing_unit?:string;rate_amount?:string;currency_code:string;valid_from?:string;valid_to?:string;active:boolean;code?:string;name?:string;description?:string;price?:string;taxable?:boolean;unit?:string;price_per_unit?:string;surcharge?:string;effective_from?:string;effective_to?:string;dop_per_unit?:string;rate_percent?:string}
export type Trip={id:string;reservation_number:string;created_at:string;status:string;pickup_at:string;return_at:string;currency_code:string;quoted_total:string;pickup_location:string;pickup_location_code:string;return_location:string;return_location_code:string;vehicle_class:string;class_code:string;supplier_name:string;comments?:string;flight_number?:string;customer?:{first_name?:string;last_name?:string;email?:string;phone_number?:string;address_line_1?:string;address_line_2?:string;city?:string;state_region?:string;postal_code?:string;country_code?:string};taxes?:Array<{tax_code:string;name:string;rate_percent:string;taxable_subtotal?:string;tax_amount?:string}>;charges:Array<{line_number:number;charge_type:string;description:string;quantity:string;unit_price:string;net_amount:string;tax_amount:string;total_amount:string;currency_code:string}>}
