import {useEffect,useState} from 'react'
import {ArrowRight,CalendarDays,Car,Check,ChevronDown,Clock3,Fuel,Headphones,Heart,KeyRound,Luggage,MapPin,Menu,Search,ShieldCheck,SlidersHorizontal,Sparkles,Star,Users,X} from 'lucide-react'
import {api,auth,type AuthResponse,type BookingResult,type Car as CarType,type Location} from './api'

const localDate=(plusDays:number,hour=10)=>{const d=new Date();d.setDate(d.getDate()+plusDays);d.setHours(hour,0,0,0);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const money=(value:string,currency:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value))

export default function App(){
 const [brand,setBrand]=useState('Northstar Drive'),[locations,setLocations]=useState<Location[]>([]),[pickup,setPickup]=useState(''),[dropoff,setDropoff]=useState(''),[pickupAt,setPickupAt]=useState(localDate(2)),[returnAt,setReturnAt]=useState(localDate(5)),[age,setAge]=useState(30)
 const [cars,setCars]=useState<CarType[]>([]),[searched,setSearched]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<CarType|null>(null),[authOpen,setAuthOpen]=useState(false),[customer,setCustomer]=useState<AuthResponse['customer']|null>(null),[confirmation,setConfirmation]=useState<BookingResult|null>(null)
 useEffect(()=>{api.brand().then(x=>setBrand(x.name));api.locations().then(items=>{setLocations(items);if(items[0]){setPickup(items[0].id);setDropoff(items[0].id)}}).catch(e=>setError(e.message))},[])
 const search=async()=>{if(!pickup||!dropoff)return;setLoading(true);setError('');try{const q=new URLSearchParams({pickup_location_id:pickup,return_location_id:dropoff,pickup_at:new Date(pickupAt).toISOString(),return_at:new Date(returnAt).toISOString(),driver_age:String(age)});setCars((await api.search(q)).items);setSearched(true)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 const startBooking=(car:CarType)=>{setSelected(car);setConfirmation(null);if(!auth.has())setAuthOpen(true)}
 const completeBooking=async()=>{if(!selected)return;try{setLoading(true);setConfirmation(await api.book({pickup_location_id:pickup,return_location_id:dropoff,vehicle_class_id:selected.vehicle_class_id,rate_plan_price_id:selected.rate_plan_price_id,pickup_at:new Date(pickupAt).toISOString(),return_at:new Date(returnAt).toISOString(),driver_age:age}));setSelected(null)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 const route=`${locations.find(x=>x.id===pickup)?.code||''} → ${locations.find(x=>x.id===dropoff)?.code||''}`
 return <div className="consumer-app"><header className="site-header"><a className="brand"><span><Car/></span><div><strong>{brand}</strong><small>Drive your way</small></div></a><nav><a href="#cars">Find a car</a><a href="#benefits">Why us</a><a href="#support">Support</a></nav><div className="account-actions"><button className="currency">USD <ChevronDown/></button><button className="sign-in" onClick={()=>setAuthOpen(true)}><KeyRound/>{customer?`Hi, ${customer.first_name}`:'Sign in'}</button><button className="menu"><Menu/></button></div></header>
 <main><section className="hero"><div className="hero-copy"><p><Sparkles/>More freedom. More road.</p><h1>Your next adventure<br/>starts with the <em>right car.</em></h1><span>Compare great cars, transparent prices, and flexible pickup options—all in one place.</span><div className="trust"><div><b>4.8</b><span><Star/><Star/><Star/><Star/><Star/></span><small>Trusted by travelers</small></div><i/><div><ShieldCheck/><span><b>Book with confidence</b><small>Secure & flexible booking</small></span></div></div></div></section>
 <section className="search-shell"><div className="trip-toggle"><button className="active">Return to same location</button><button onClick={()=>setDropoff('')}>Different drop-off</button></div><div className="search-grid"><label className="location-field"><span>Pick-up location</span><div><MapPin/><select value={pickup} onChange={e=>{setPickup(e.target.value);if(dropoff)setDropoff(e.target.value)}}>{locations.map(x=><option key={x.id} value={x.id}>{x.name} — {x.city}</option>)}</select></div></label><label><span>Pick-up</span><div><CalendarDays/><input type="datetime-local" value={pickupAt} onChange={e=>setPickupAt(e.target.value)}/></div></label><label><span>Drop-off</span><div><CalendarDays/><input type="datetime-local" value={returnAt} onChange={e=>setReturnAt(e.target.value)}/></div></label><label><span>Driver age</span><div><Users/><input type="number" min="21" max="100" value={age} onChange={e=>setAge(Number(e.target.value))}/></div></label><button className="search-button" onClick={search}><Search/>{loading?'Searching…':'Search cars'}</button></div>{dropoff!==pickup&&<div className="different-drop"><label><span>Drop-off location</span><select value={dropoff} onChange={e=>setDropoff(e.target.value)}><option value="">Choose location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>}</section>
 {error&&<div className="error-banner">{error}<button onClick={()=>setError('')}><X/></button></div>}
 {!searched?<Landing search={search}/>:<Results cars={cars} route={route} pickupAt={pickupAt} returnAt={returnAt} onSelect={startBooking}/>}<section className="newsletter" id="benefits"><div><p className="eyebrow">THE OPEN ROAD, DELIVERED</p><h2>Travel inspiration and member-only deals.</h2></div><button onClick={()=>setAuthOpen(true)}>Create free account <ArrowRight/></button></section></main>
 <footer><div className="brand"><span><Car/></span><div><strong>{brand}</strong><small>Drive your way</small></div></div><p>© 2026 {brand}. Built for better journeys.</p></footer>
 {authOpen&&<AuthModal onClose={()=>setAuthOpen(false)} onDone={(data)=>{auth.set(data.access_token);setCustomer(data.customer);setAuthOpen(false)}}/>}
 {selected&&auth.has()&&<div className="modal-backdrop"><section className="booking-modal"><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">YOUR SELECTION</p><h2>Complete your reservation</h2><div className="booking-car"><span><Car/></span><div><h3>{selected.name}</h3><p>{selected.make} {selected.model} or similar</p><small>{route}</small></div><strong>{money(selected.total,selected.currency_code)}</strong></div><div className="booking-summary"><p><span>Rental period</span><b>{selected.rental_days} days</b></p><p><span>Daily price</span><b>{money(selected.rate_amount,selected.currency_code)}</b></p><p><span>Due at counter</span><b>{money(selected.total,selected.currency_code)}</b></p></div><label className="terms"><input type="checkbox" defaultChecked/>I agree to the rental terms and cancellation policy.</label><button className="confirm-button" onClick={completeBooking} disabled={loading}>{loading?'Reserving…':'Confirm reservation'}<ArrowRight/></button></section></div>}
 {confirmation&&<div className="modal-backdrop"><section className="success-modal"><span><Check/></span><p className="eyebrow">YOU'RE ALL SET</p><h2>Reservation confirmed</h2><p>Your confirmation number is</p><strong>{confirmation.reservation_number}</strong><p>We’ll keep your car ready for pickup.</p><button onClick={()=>setConfirmation(null)}>Done</button></section></div>}</div>
}

function Landing({search}:{search:()=>void}){return <><section className="intro-strip"><div><span><ShieldCheck/></span><b>No hidden fees</b><small>Know exactly what you pay</small></div><div><span><Clock3/></span><b>Flexible changes</b><small>Plans change. We understand.</small></div><div><span><Headphones/></span><b>Local support</b><small>Real help when you need it</small></div></section><section className="featured" id="cars"><p className="eyebrow">POPULAR CHOICES</p><h2>Find a car for every kind of trip</h2><span>From city-friendly compacts to spacious SUVs.</span><div className="category-grid">{[['City & Compact','Easy parking, effortless exploring','From $42/day','compact'],['SUVs & Crossovers','More space for every adventure','From $68/day','suv'],['Premium & Luxury','Arrive in comfort and style','From $110/day','premium']].map(x=><article className={x[3]} key={x[0]}><div className="car-art"><Car/></div><p>{x[0]}</p><small>{x[1]}</small><b>{x[2]}</b><button onClick={search}>Explore cars <ArrowRight/></button></article>)}</div></section></>}

function Results({cars,route,pickupAt,returnAt,onSelect}:{cars:CarType[];route:string;pickupAt:string;returnAt:string;onSelect:(car:CarType)=>void}){return <section className="results" id="cars"><div className="results-head"><div><p className="eyebrow">AVAILABLE NOW</p><h2>{cars.length} cars for your trip</h2><span>{route} · {new Date(pickupAt).toLocaleDateString()} – {new Date(returnAt).toLocaleDateString()}</span></div><button><SlidersHorizontal/>Filter & sort</button></div><div className="results-list">{cars.map((car,index)=><article className="car-result" key={car.rate_plan_price_id}><div className="car-visual"><span>{index===0?'BEST VALUE':car.available_count<=2?'ONLY A FEW LEFT':'GREAT CHOICE'}</span><Car/></div><div className="car-info"><div className="car-title"><div><small>{car.class_code}</small><h3>{car.name}</h3><p>{car.make} {car.model} or similar</p></div><button><Heart/></button></div><div className="specs"><span><Users/>{car.passenger_capacity} seats</span><span><Luggage/>{car.luggage_capacity} bags</span><span><Car/>{car.transmission?.toLowerCase()}</span><span><Fuel/>{car.fuel_type?.toLowerCase()}</span></div><div className="included"><span><Check/>Free cancellation</span><span><Check/>Unlimited mileage</span></div></div><div className="price-card"><small>Price for {car.rental_days} days</small><strong>{money(car.total,car.currency_code)}</strong><span>{money(car.rate_amount,car.currency_code)} / day</span><em>Taxes included where applicable</em><button onClick={()=>onSelect(car)}>Reserve <ArrowRight/></button><small>{car.available_count} available</small></div></article>)}{cars.length===0&&<div className="empty"><Car/><h3>No cars match this trip yet</h3><p>Try another date or pickup location.</p></div>}</div></section>}

function AuthModal({onClose,onDone}:{onClose:()=>void;onDone:(data:AuthResponse)=>void}){const [mode,setMode]=useState<'login'|'register'>('login'),[form,setForm]=useState({first_name:'',last_name:'',email:'',phone:'',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setError('');try{onDone(mode==='login'?await api.login({email:form.email,password:form.password}):await api.register(form))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return <div className="modal-backdrop"><section className="auth-modal"><button className="modal-close" onClick={onClose}><X/></button><span className="auth-icon"><KeyRound/></span><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p>{mode==='login'?'Sign in to book faster and see your trips.':'Save your details and manage every journey.'}</p>{mode==='register'&&<div className="name-row"><label>First name<input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div>}<label>Email address<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>{mode==='register'&&<label>Phone number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>}<label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="auth-error">{error}</div>}<button className="confirm-button" onClick={submit} disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}<ArrowRight/></button><p className="switch-auth">{mode==='login'?"New here? ":'Already have an account? '}<button onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create account':'Sign in'}</button></p></section></div>}
