import {useEffect,useState} from 'react'
import {ArrowRight,CalendarDays,Car,Check,ChevronDown,Clock3,Fuel,Headphones,Heart,KeyRound,Luggage,MapPin,Menu,Search,ShieldCheck,SlidersHorizontal,Sparkles,Star,Users,X} from 'lucide-react'
import {api,auth,type AuthResponse,type BookingResult,type Car as CarType,type Location} from './api'

const localDate=(plusDays:number,hour=10)=>{const d=new Date();d.setDate(d.getDate()+plusDays);d.setHours(hour,0,0,0);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
type Language='en'|'es';type DisplayCurrency='USD'|'DOP'
const tr=(language:Language,en:string,es:string)=>language==='es'?es:en
const displayMoney=(value:string,source:string,target:DisplayCurrency,usdToDop:number,language:Language)=>{let amount=Number(value);if(source==='USD'&&target==='DOP')amount*=usdToDop;else if(source==='DOP'&&target==='USD')amount/=usdToDop;return new Intl.NumberFormat(language==='es'?'es-DO':'en-US',{style:'currency',currency:target,maximumFractionDigits:0}).format(amount)}

function DominicanLogo(){return <span className="dominican-logo" aria-hidden="true"><i/><i/><i/><i/><Car/></span>}

export default function App(){
 const [brand,setBrand]=useState('Dominican Rentals'),[usdToDop,setUsdToDop]=useState(60),[language,setLanguage]=useState<Language>(()=>(localStorage.getItem('booking_language') as Language)||'es'),[displayCurrency,setDisplayCurrency]=useState<DisplayCurrency>(()=>(localStorage.getItem('booking_currency') as DisplayCurrency)||'USD'),[locations,setLocations]=useState<Location[]>([]),[pickup,setPickup]=useState(''),[dropoff,setDropoff]=useState(''),[pickupAt,setPickupAt]=useState(localDate(2)),[returnAt,setReturnAt]=useState(localDate(5)),[age,setAge]=useState(30)
 const [cars,setCars]=useState<CarType[]>([]),[searched,setSearched]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<CarType|null>(null),[authOpen,setAuthOpen]=useState(false),[customer,setCustomer]=useState<AuthResponse['customer']|null>(null),[confirmation,setConfirmation]=useState<BookingResult|null>(null)
 useEffect(()=>{api.brand().then(x=>{setBrand(x.name);setUsdToDop(Number(x.usd_to_dop)||60)});api.locations().then(items=>{setLocations(items);if(items[0]){setPickup(items[0].id);setDropoff(items[0].id)}}).catch(e=>setError(e.message))},[])
 const chooseLanguage=(value:Language)=>{setLanguage(value);localStorage.setItem('booking_language',value)}
 const chooseCurrency=(value:DisplayCurrency)=>{setDisplayCurrency(value);localStorage.setItem('booking_currency',value)}
 const search=async()=>{if(!pickup||!dropoff)return;setLoading(true);setError('');try{const q=new URLSearchParams({pickup_location_code:pickup,return_location_code:dropoff,pickup_at:new Date(pickupAt).toISOString(),return_at:new Date(returnAt).toISOString(),driver_age:String(age)});setCars((await api.search(q)).items);setSearched(true)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 const startBooking=(car:CarType)=>{setSelected(car);setConfirmation(null);if(!auth.has())setAuthOpen(true)}
 const completeBooking=async()=>{if(!selected)return;try{setLoading(true);setConfirmation(await api.book({pickup_location_id:selected.pickup_location_id,return_location_id:selected.return_location_id,vehicle_class_id:selected.vehicle_class_id,rate_plan_price_id:selected.rate_plan_price_id,pickup_at:new Date(pickupAt).toISOString(),return_at:new Date(returnAt).toISOString(),driver_age:age}));setSelected(null)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 const route=`${locations.find(x=>x.id===pickup)?.code||''} → ${locations.find(x=>x.id===dropoff)?.code||''}`
 return <div className="consumer-app"><header className="site-header"><a className="brand"><DominicanLogo/><div><strong>{brand}</strong><small>{tr(language,'Drive your way','Conduce a tu manera')}</small></div></a><nav><a href="#cars">{tr(language,'Find a car','Buscar vehículo')}</a><a href="#benefits">{tr(language,'Why us','Por qué nosotros')}</a><a href="#support">{tr(language,'Support','Ayuda')}</a></nav><div className="account-actions"><div className="preference-toggle" aria-label="Language"><button className={language==='en'?'active':''} onClick={()=>chooseLanguage('en')}>EN</button><button className={language==='es'?'active':''} onClick={()=>chooseLanguage('es')}>ES</button></div><div className="preference-toggle currency-toggle" aria-label="Currency"><button className={displayCurrency==='USD'?'active':''} onClick={()=>chooseCurrency('USD')}>USD</button><button className={displayCurrency==='DOP'?'active':''} onClick={()=>chooseCurrency('DOP')}>DOP</button></div><button className="sign-in" onClick={()=>setAuthOpen(true)}><KeyRound/>{customer?`${tr(language,'Hi','Hola')}, ${customer.first_name}`:tr(language,'Sign in','Ingresar')}</button><button className="menu"><Menu/></button></div></header>
 <main><section className="hero"><div className="hero-copy"><p><Sparkles/>{tr(language,'More freedom. More road.','Más libertad. Más camino.')}</p><h1>{tr(language,'Your next adventure','Tu próxima aventura')}<br/>{tr(language,'starts with the','comienza con el')} <em>{tr(language,'right car.','vehículo ideal.')}</em></h1><span>{tr(language,'Compare great cars, transparent prices, and flexible pickup options—all in one place.','Compara excelentes vehículos, precios transparentes y opciones flexibles de recogida, todo en un solo lugar.')}</span><div className="trust"><div><b>4.8</b><span><Star/><Star/><Star/><Star/><Star/></span><small>{tr(language,'Trusted by travelers','La confianza de viajeros')}</small></div><i/><div><ShieldCheck/><span><b>{tr(language,'Book with confidence','Reserva con confianza')}</b><small>{tr(language,'Secure & flexible booking','Reserva segura y flexible')}</small></span></div></div></div></section>
 <section className="search-shell"><div className="trip-toggle"><button className="active">{tr(language,'Return to same location','Devolver en el mismo lugar')}</button><button onClick={()=>setDropoff('')}>{tr(language,'Different drop-off','Devolver en otro lugar')}</button></div><div className="search-grid"><label className="location-field"><span>{tr(language,'Pick-up location','Lugar de recogida')}</span><div><MapPin/><select value={pickup} onChange={e=>{setPickup(e.target.value);if(dropoff)setDropoff(e.target.value)}}>{locations.map(x=><option key={x.id} value={x.id}>{x.name} — {x.city}</option>)}</select></div></label><label><span>{tr(language,'Pick-up','Recogida')}</span><div><CalendarDays/><input type="datetime-local" value={pickupAt} onChange={e=>setPickupAt(e.target.value)}/></div></label><label><span>{tr(language,'Drop-off','Devolución')}</span><div><CalendarDays/><input type="datetime-local" value={returnAt} onChange={e=>setReturnAt(e.target.value)}/></div></label><label><span>{tr(language,'Driver age','Edad')}</span><div><Users/><input type="number" min="21" max="100" value={age} onChange={e=>setAge(Number(e.target.value))}/></div></label><button className="search-button" onClick={search}><Search/>{loading?tr(language,'Searching…','Buscando…'):tr(language,'Search cars','Buscar vehículos')}</button></div>{dropoff!==pickup&&<div className="different-drop"><label><span>{tr(language,'Drop-off location','Lugar de devolución')}</span><select value={dropoff} onChange={e=>setDropoff(e.target.value)}><option value="">{tr(language,'Choose location','Selecciona un lugar')}</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>}</section>
 {error&&<div className="error-banner">{error}<button onClick={()=>setError('')}><X/></button></div>}
 {!searched?<Landing search={search} language={language}/>:<Results cars={cars} route={route} pickupAt={pickupAt} returnAt={returnAt} onSelect={startBooking} language={language} displayCurrency={displayCurrency} usdToDop={usdToDop}/>}<section className="newsletter" id="benefits"><div><p className="eyebrow">{tr(language,'THE OPEN ROAD, DELIVERED','EL CAMINO ABIERTO TE ESPERA')}</p><h2>{tr(language,'Travel inspiration and member-only deals.','Inspiración para viajar y ofertas exclusivas.')}</h2></div><button onClick={()=>setAuthOpen(true)}>{tr(language,'Create free account','Crear cuenta gratis')} <ArrowRight/></button></section></main>
 <footer><div className="brand"><DominicanLogo/><div><strong>{brand}</strong><small>{tr(language,'Drive your way','Conduce a tu manera')}</small></div></div><p>© 2026 {brand}. {tr(language,'Built for better journeys.','Creado para mejores viajes.')}</p></footer>
 {authOpen&&<AuthModal language={language} onClose={()=>setAuthOpen(false)} onDone={(data)=>{auth.set(data.access_token);setCustomer(data.customer);setAuthOpen(false)}}/>}
 {selected&&auth.has()&&<div className="modal-backdrop"><section className="booking-modal"><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">{tr(language,'YOUR SELECTION','TU SELECCIÓN')}</p><h2>{tr(language,'Complete your reservation','Completa tu reserva')}</h2><div className="booking-car"><span><Car/></span><div><h3>{selected.name}</h3><p>{selected.make||selected.name} {selected.model||''} {tr(language,'or similar','o similar')}</p><small>{route} · {tr(language,'Supplied by','Suministrado por')} {selected.supplier_name}</small></div><strong>{displayMoney(selected.total,selected.currency_code,displayCurrency,Number(selected.usd_to_dop)||usdToDop,language)}</strong></div><div className="booking-summary"><p><span>{tr(language,'Rental period','Período de alquiler')}</span><b>{selected.rental_days} {tr(language,'days','días')}</b></p><p><span>{tr(language,'Daily price','Precio diario')}</span><b>{displayMoney(selected.rate_amount,selected.currency_code,displayCurrency,Number(selected.usd_to_dop)||usdToDop,language)}</b></p><p><span>{tr(language,'Due at counter','A pagar en el mostrador')}</span><b>{displayMoney(selected.total,selected.currency_code,displayCurrency,Number(selected.usd_to_dop)||usdToDop,language)}</b></p></div><label className="terms"><input type="checkbox" defaultChecked/>{tr(language,'I agree to the rental terms and cancellation policy.','Acepto los términos de alquiler y la política de cancelación.')}</label><button className="confirm-button" onClick={completeBooking} disabled={loading}>{loading?tr(language,'Reserving…','Reservando…'):tr(language,'Confirm reservation','Confirmar reserva')}<ArrowRight/></button></section></div>}
 {confirmation&&<div className="modal-backdrop"><section className="success-modal"><span><Check/></span><p className="eyebrow">{tr(language,"YOU'RE ALL SET",'TODO LISTO')}</p><h2>{tr(language,'Reservation confirmed','Reserva confirmada')}</h2><p>{tr(language,'Your confirmation number is','Tu número de confirmación es')}</p><strong>{confirmation.reservation_number}</strong><p>{tr(language,"We’ll keep your car ready for pickup.",'Tendremos tu vehículo listo para la recogida.')}</p><button onClick={()=>setConfirmation(null)}>{tr(language,'Done','Listo')}</button></section></div>}</div>
}

function Landing({search,language}:{search:()=>void;language:Language}){const choices=language==='es'?[['Ciudad y compacto','Fácil de estacionar, fácil de explorar','Desde US$42/día','compact'],['SUVs y crossovers','Más espacio para cada aventura','Desde US$68/día','suv'],['Premium y lujo','Llega con comodidad y estilo','Desde US$110/día','premium']]:[['City & Compact','Easy parking, effortless exploring','From $42/day','compact'],['SUVs & Crossovers','More space for every adventure','From $68/day','suv'],['Premium & Luxury','Arrive in comfort and style','From $110/day','premium']];return <><section className="intro-strip"><div><span><ShieldCheck/></span><b>{tr(language,'No hidden fees','Sin cargos ocultos')}</b><small>{tr(language,'Know exactly what you pay','Conoce exactamente lo que pagas')}</small></div><div><span><Clock3/></span><b>{tr(language,'Flexible changes','Cambios flexibles')}</b><small>{tr(language,'Plans change. We understand.','Los planes cambian. Lo entendemos.')}</small></div><div><span><Headphones/></span><b>{tr(language,'Local support','Asistencia local')}</b><small>{tr(language,'Real help when you need it','Ayuda real cuando la necesitas')}</small></div></section><section className="featured" id="cars"><p className="eyebrow">{tr(language,'POPULAR CHOICES','OPCIONES POPULARES')}</p><h2>{tr(language,'Find a car for every kind of trip','Encuentra un vehículo para cada viaje')}</h2><span>{tr(language,'From city-friendly compacts to spacious SUVs.','Desde compactos para la ciudad hasta SUVs espaciosos.')}</span><div className="category-grid">{choices.map(x=><article className={x[3]} key={x[0]}><div className="car-art"><Car/></div><p>{x[0]}</p><small>{x[1]}</small><b>{x[2]}</b><button onClick={search}>{tr(language,'Explore cars','Explorar vehículos')} <ArrowRight/></button></article>)}</div></section></>}

function Results({cars,route,pickupAt,returnAt,onSelect,language,displayCurrency,usdToDop}:{cars:CarType[];route:string;pickupAt:string;returnAt:string;onSelect:(car:CarType)=>void;language:Language;displayCurrency:DisplayCurrency;usdToDop:number}){
 return <section className="results" id="cars"><div className="results-head"><div><p className="eyebrow">{tr(language,'AVAILABLE NOW','DISPONIBLE AHORA')}</p><h2>{cars.length} {tr(language,'rates for your trip','tarifas para tu viaje')}</h2><span>{route} · {new Date(pickupAt).toLocaleDateString(language==='es'?'es-DO':'en-US')} – {new Date(returnAt).toLocaleDateString(language==='es'?'es-DO':'en-US')}</span></div><button><SlidersHorizontal/>{tr(language,'Filter & sort','Filtrar y ordenar')}</button></div><div className="results-list">
 {cars.map((car,index)=>{const exchange=Number(car.usd_to_dop)||usdToDop;return <article className="car-result" key={`${car.supplier_company_id}-${car.rate_plan_price_id}`}><div className="car-visual"><span>{index===0?tr(language,'BEST VALUE','MEJOR PRECIO'):tr(language,'PUBLISHED RATE','TARIFA PUBLICADA')}</span><Car/></div><div className="car-info"><div className="car-title"><div><small>{car.class_code}</small><h3>{car.name}</h3><p>{car.make||car.name} {car.model||''} {tr(language,'or similar','o similar')}</p></div><button><Heart/></button></div><div className="supplier-line"><ShieldCheck/><span>{tr(language,'Supplied by','Suministrado por')} <strong>{car.supplier_name}</strong></span></div><div className="specs"><span><Users/>{car.passenger_capacity} {tr(language,'seats','asientos')}</span><span><Luggage/>{car.luggage_capacity} {tr(language,'bags','maletas')}</span><span><Car/>{tr(language,car.transmission?.toLowerCase()||'',car.transmission==='AUTOMATIC'?'automático':car.transmission?.toLowerCase()||'')}</span><span><Fuel/>{tr(language,car.fuel_type?.toLowerCase()||'',car.fuel_type==='GASOLINE'?'gasolina':car.fuel_type?.toLowerCase()||'')}</span></div><div className="included"><span><Check/>{tr(language,'Free cancellation','Cancelación gratis')}</span><span><Check/>{tr(language,'Published by the supplier','Publicada por el proveedor')}</span></div></div><div className="price-card"><small>{tr(language,'Price for','Precio por')} {car.rental_days} {tr(language,'days','días')}</small><strong>{displayMoney(car.total,car.currency_code,displayCurrency,exchange,language)}</strong><span>{displayMoney(car.rate_amount,car.currency_code,displayCurrency,exchange,language)} / {tr(language,'day','día')}</span><em>{tr(language,'Supplier base rate','Tarifa base del proveedor')}</em><button onClick={()=>onSelect(car)}>{tr(language,'Reserve','Reservar')} <ArrowRight/></button></div></article>})}
 {cars.length===0&&<div className="empty"><Car/><h3>{tr(language,'No published rates match this trip yet','Aún no hay tarifas publicadas para este viaje')}</h3><p>{tr(language,'Try another date or pickup location.','Prueba otra fecha o lugar de recogida.')}</p></div>}</div></section>
}

function AuthModal({onClose,onDone,language}:{onClose:()=>void;onDone:(data:AuthResponse)=>void;language:Language}){const [mode,setMode]=useState<'login'|'register'>('login'),[form,setForm]=useState({first_name:'',last_name:'',email:'',phone:'',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setError('');try{onDone(mode==='login'?await api.login({email:form.email,password:form.password}):await api.register(form))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return <div className="modal-backdrop"><section className="auth-modal"><button className="modal-close" onClick={onClose}><X/></button><span className="auth-icon"><KeyRound/></span><h2>{mode==='login'?tr(language,'Welcome back','Bienvenido de nuevo'):tr(language,'Create your account','Crea tu cuenta')}</h2><p>{mode==='login'?tr(language,'Sign in to book faster and see your trips.','Ingresa para reservar más rápido y ver tus viajes.'):tr(language,'Save your details and manage every journey.','Guarda tus datos y administra cada viaje.')}</p>{mode==='register'&&<div className="name-row"><label>{tr(language,'First name','Nombre')}<input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>{tr(language,'Last name','Apellido')}<input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div>}<label>{tr(language,'Email address','Correo electrónico')}<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>{mode==='register'&&<label>{tr(language,'Phone number','Teléfono')}<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>}<label>{tr(language,'Password','Contraseña')}<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="auth-error">{error}</div>}<button className="confirm-button" onClick={submit} disabled={busy}>{busy?tr(language,'Please wait…','Espera…'):mode==='login'?tr(language,'Sign in','Ingresar'):tr(language,'Create account','Crear cuenta')}<ArrowRight/></button><p className="switch-auth">{mode==='login'?tr(language,'New here? ','¿Eres nuevo? '):tr(language,'Already have an account? ','¿Ya tienes cuenta? ')}<button onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?tr(language,'Create account','Crear cuenta'):tr(language,'Sign in','Ingresar')}</button></p></section></div>}
